---

cuckoo_req:
    - python
    - python-pip
    - python-dev
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - mongodb
    - python-virtualenv
    - python-setuptools
    - libjpeg-dev
    - zlib1g-dev
    - swig
    - tcpdump
    - libcap2-bin
    - libyara-dev

cuckoo_kvm:
    - qemu-kvm
    - libvirt-bin
    - ubuntu-vm-builder
    - bridge-utils
    - python-libvirt
