---

- name: pip | install python package dependencies
  pip:
      name: "{{ pip_pkg }}"
      state: present
      virtualenv: "{{ cuckoo_virtenv }}"
      virtualenv_command: virtualenv
      virtualenv_python: python2.7
  register: pkg_status
  failed_when: pkg_status is failed

- name: pip | install cuckoo sandbox inside virtualenv
  pip:
      name: cuckoo
      state: present
      virtualenv: "{{ cuckoo_virtenv }}"
      virtualenv_command: virtualenv
      virtualenv_python: python2.7
  register: result
  failed_when: pkg_status is failed

- name: cuckoo | config CWD
  become: yes
  become_user: "{{ cuckoo_user }}"
  command: "{{ cuckoo_virtenv }}/bin/cuckoo --cwd {{ cuckoo_cwd }}"
  args:
    creates: "{{ cuckoo_cwd }}/__init__.py"
