---

- name: bash | configure tcpdump cuz we don't wanna give cuckoo root user!
  become: true
  shell: |
    aa-disable {{ tcpdump_path }}
    groupadd {{ pcap_group }}
    usermod -aG {{ pcap_group }} {{ cuckoo_user }}
    chgrp {{ pcap_group }} {{ tcpdump_path }}
    setcap cap_net_raw,cap_net_admin=eip {{ tcpdump_path }}
  args:
    executable: /bin/bash
  register: result
  failed_when: result is failed
